### ISSUE TITLE
 sunset ZEIT Now 1.0 service is going down!

### ISSUE THREAD

**Issue by shilik** [martinheidegger/kuromoji-vercel#1]
Hi @martinheidegger 

Thanks for your great project. I have used it in my own project and it works very well until I got the follow message from [.](https://mailchi.mp/f923e55efe1d/simplified-pricing-1087517)
Is there anyway to make it live again?
<img width="645" alt="Snipaste_2020-08-12_20-48-54" src="https://user-images.githubusercontent.com/1404868/90016915-52027f80-dcdd-11ea-9180-946567d5a887.png">

**Comment by martinheidegger** [comment]
Updated the APP to use vercel and functions. Thank you for pinging me.
